In [1]:
import torch

In [2]:
a = torch.rand([1,2])
a

tensor([[0.9397, 0.8339]])

In [6]:
torch.nn.Identity(a=0,s=0,d=11)(a)

tensor([[0.9397, 0.8339]])

In [7]:
import gym

In [8]:
env = gym.make('CartPole-v0')

In [9]:
env.reset()

array([-0.03366987,  0.01920591,  0.02328142, -0.0339521 ])

In [21]:
obs, rew, done, _ = env.step(0)

In [22]:
rew

1.0

In [23]:
a = [1,2,3,4,5,6,7]
ep_ret = sum(a)

In [25]:
weights = []
weights += [ep_ret] * 7

In [26]:
weights

[28, 28, 28, 28, 28, 28, 28]

In [27]:
import numpy as np
np.zeros(range(10))

array([], shape=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9), dtype=float64)